name: Compare APK
on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'api/**'
      - 'client/flutter/**'
jobs:
  build-master:
    name: Build master Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.12.13+hotfix.8 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
        working-directory: ./client/flutter
      - run: |
            flutter build apk
            mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/app-master.apk
        working-directory: ./client/flutter
      - name: Upload master apk
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: client/flutter/build/app/outputs/apk/release/app-master.apk
  build-new:
    name: Build incoming Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.12.13+hotfix.8 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
        working-directory: ./client/flutter
      - run: |
            flutter build apk
            mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/app-pr.apk
        working-directory: ./client/flutter
      - name: Upload pr apk
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: client/flutter/build/app/outputs/apk/release/app-pr.apk
  setup-diffuse:
    name: Setup diffuse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/JakeWharton/diffuse.git
      - name: generate diffuse
        run: ./gradlew assemble
        working-directory: diffuse
      - name: Upload diffuse executable
        uses: actions/upload-artifact@v1
        with:
          name: diff
          path: diffuse/diffuse/build/diffuse
  diffuse:
    needs: [build-master, build-new]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Download diffuse executable
        uses: actions/download-artifact@v1
        with:
          name: diff
      - name: Change diffuse permissions
        run: |
            ls
            chmod +x ./diffuse
        working-directory: diff
      - name: Execute Diffuse
        run: ./diff/diffuse diff apk/app-master.apk apk/app-pr.apk
